spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
  #    open-in-view: false #?????? ?? ?????????? ? ?????????????? ??
  datasource:
#    url: jdbc:postgresql://172.30.38.105:5432/app_news
    url: jdbc:postgresql://localhost:5430/todo_app
    username: postgres
    password: postgres
    hikari:
      schema: todo_app
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS todo_app
      connection-timeout: 10000
