version: '3'
services:
  postgres:
    image: postgres:15.5
    container_name: todo
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_app
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql